---
name: Build, Deploy to GitHub Pages and Deploy PR Preview
author: WATAHIKI Yuto
description: Build, Deploy to GitHub Pages and Deploy PR Preview
inputs:
  type:
    description: Type of the project(`vite` is the only supported type for now)
    required: true
  rootDir:
    description: Root directory of the project
    required: false
    default: .
  folder:
    description: Folder to deploy(If set to auto, it will use the default folder for the type of the project.)
    required: false
    default: auto
  pr-preview:
    description: Whether to deploy PR Preview(`true` or `false`)
    required: false
    default: true
  branch:
    description: Branch to deploy
    required: false
    default: gh-pages
  umbrella-dir:
    description: Directory containing all previews
    required: false
    default: pr-preview

runs:
  using: composite
  steps:
    - name: Determine the folder to deploy
      id: folder
      uses: actions/github-script@v6
      with:
        script: |
          const typeInput = "${{ inputs.type }}";
          const folderInput = "${{ inputs.folder }}";
          if (folderInput === "auto") {
            if (typeInput === "vite") {
              return "dist";
            }
          } else {
            return folderInput;
          }
        result-encoding: string

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: latest

    - name: Cache npm packages
      id: npm-cache
      uses: actions/cache@v3
      with:
        path: "**/node_modules"
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: Install npm packages
      if: steps.npm-cache.outputs.cache-hit != 'true'
      working-directory: ${{ inputs.rootDir }}
      run: npm ci
      shell: bash

    - name: Build Vite project
      if: ${{ inputs.type == 'vite' }}
      working-directory: ${{ inputs.rootDir }}
      run: npx vite build
      shell: bash

    - name: Deploy to GitHub Pages
      if: ${{ github.event_name == 'push' }}
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: ${{ steps.folder.outputs.result }}
        branch: ${{ inputs.branch }}
        clean-exclude: ${{ inputs.umbrella-dir }}

    - name: Deploy PR Preview
      if: ${{ github.event_name == 'pull_request' && inputs.pr-preview == 'true' }}
      uses: rossjrw/pr-preview-action@v1
      with:
        source-dir: ${{ steps.folder.outputs.result }}
        preview-branch: ${{ inputs.branch }}
        umbrella-dir: ${{ inputs.umbrella-dir }}

branding:
  icon: git-branch
  color: gray-dark
